### ISSUE TITLE
Warning: Animated.event now requires second argument

### ISSUE THREAD

**Issue by elahaha** [JungHsuan/rn-gesture-flip-card#4]
HI JH, 
I really like your flip card component, but currently facing a warning in v.1.0.3
Among others you find a related discussion [here](https://github.com/nysamnang/react-native-raw-bottom-sheet/issues/81).
And react-native changes [here](https://github.com/facebook/react-native/commit/b48f7e560545d53db7c906ced51a91c4cce6ee94).

Fix should look something ike this: 
return Animated.event([null, {dx: this.state.scrollX}], **{useNativeDriver: bool}**)(
        evt,
        gestureState,
);

Let me know what you are thinking.

**Comment by JungHsuan** [comment]
@elahaha Thanks! I totally agree. I will fix that ASAP.

**Comment by JungHsuan** [comment]
I just published v1.0.4!

**Comment by elahaha** [comment]
useNativeDriver: **true**, leads to 
`TypeError: AnimatedEvent is not a function (near '...})(evt, gestureState);...')`
on my end, whereas setting it to **false**, works perfectly fine - could be attributed to my pretty ancient Android phone

**Comment by JungHsuan** [comment]
@elahaha Hi, that was my mistake, ``PanResponder`` run only on JS thread, so setting ``useNativeDriver`` to true cause error.
